import { realtimeEmitter, REALTIME_EVENTS } from "./realtimeEmitter"

export const dashboardEmitter = realtimeEmitter
export const DASHBOARD_EVENTS = {
  TICKETS_CHANGED: REALTIME_EVENTS.TICKETS_CHANGED,
  RMA_CHANGED: REALTIME_EVENTS.RMA_CHANGED,
  EQUIPMENTS_CHANGED: REALTIME_EVENTS.EQUIPMENTS_CHANGED,
  STATIONS_CHANGED: REALTIME_EVENTS.STATIONS_CHANGED,
}
